variable "region" {}
variable "project_name" {}
variable "ccl-vpc-cidr_block" {}
variable "tenancy" {}
variable "host_name" {}
variable "web-public_cidrs" {}
variable "app-private_cidrs" {}
variable "subnet_ids" {}
variable "azs" {}
variable "ccl-rt" {}
variable "ccl-rt-cidr_block" {}
variable "ccl-sg" {}
variable "ccl-ssh-port" {}
variable "ssh-port" {}
variable "ccl-http-port" {}
variable "http-port" {}
variable "mysqlport" {}
variable "port" {}
variable "protocol_type" {}
variable "ccl-port" {}
variable "egress-port" {}
variable "egress-protocol" {}
variable "aws_instance-ccl-server" {}
variable "instance_type" {}
variable "ccl-ten" {}
variable "engine" {}
variable "engine_version" {}
variable "instance_class" {}
variable "allocated_storage" {}
variable "storage_type" {}
variable "identifier" {}
variable "username" {}
variable "password" {}
variable "multi_az" {}
